version: '3'

services:
  web:
    build: ./.docker
    working_dir: /var/www
    networks:
      - mysql
      - pgsql
    depends_on:
      - mysql
      - pgsql
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .:/var/www
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/99-php.ini
      - ./.docker/apache/vhosts/localhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/apache/vhosts/localhost-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DOCUMENT_ROOT=/var/www/public_html
      - APACHE_LOG_DIR=/var/www/.docker/apache/logs

  mysql:
    image: mysql:5.7
    networks:
      - mysql
    ports:
      - '3306:3306'
    volumes:
      - './.docker/mysql/data:/var/lib/mysql'
      - './.docker/mysql/settings:/etc/mysql/conf.d'
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development

  #  phpmyadmin:
  #    image: phpmyadmin/phpmyadmin
  #    networks:
  #      - mysql
  #    depends_on:
  #      - mysql
  #    environment:
  #      PMA_HOST: mysql
  #      PMA_PORT: 3306
  #    ports:
  #      - '8080:80'

  pgsql:
    image: postgres:alpine
    networks:
      - pgsql
    ports:
      - '5432:5432'
    volumes:
      - './.docker/postgres/data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=development

networks:
  mysql:
  pgsql:
